### ISSUE TITLE
Filter by Tags

### ISSUE THREAD

**Issue by kordianbruck** [kordianbruck/miniflux#1]
Still need to implement the filtering on the main page / feed lists.

**Comment by mkresin** [comment]
Implemented on
- unread page
- history page

I see no need to use filtering at the feed-items or bookmarks page.

What is your opinion on this?

**Comment by kordianbruck** [comment]
Bookmarks maybe, but I think this should be just fine for the start. We can always come back later to this.

**Comment by mkresin** [comment]
As far as I can see, no other feed reader has group/feed filtering for bookmarks/stared/favs. IMHO it's out of scope of a minimal solution.

Do you agree to close the ticket?

**Comment by kordianbruck** [comment]
Yeha!
