### ISSUE TITLE
Add untagged feed to default tag uncategorised

### ISSUE THREAD

**Issue by mkresin** [kordianbruck/miniflux#10]
It's needed:
- to show feeds within the treeview, which are not tagged, but tagging is used
- as fallback if someone doesn't use tagging at all

If this tag is the only existing tag, the treeview (#4) will not be shown.

This tag isn't visible or selectable within the feed add or edit dialog. It's automatically assigned if no tag is chosen.

This tag is a protected one and will never be purged.

**Comment by mkresin** [comment]
@kordianbruck feel free to propose a better name for this tag.

**Comment by kordianbruck** [comment]
Is it really needed? I mean you don't actually need a tag in the database called untagged with the relationship to the feeds. You check if a feed is untagged by fetching the feeds relations to the tags, if there are none, its not categorized. 

In the end this would be a UI only thing and not be needed to be implemented in the database or the save logic. Am I thinking this through right?

For the showing it in the tree: you could simply order by the join condition and get all the empty ones first. Then in the views for loop you have the not categorized feeds first and then the tagged ones. Makes sense?

**Comment by mkresin** [comment]
> Is it really needed? I mean you don't actually need a tag in the database called untagged with the relationship to the feeds. You check if a feed is untagged by fetching the feeds relations to the tags, if there are none, its not categorized. 

Yeah that's right. But you would have to implemented this logic to all functions that deal with feeds/tags. Even adding this 'information' by altering the result set of the database query needs to be done for more than one function.

From my point of view, multiple functions have to do the same job, which is somewhat not desirable. Furthermore this could lead to a lot of conditional handling depending on the presence of a tags or not.

> In the end this would be a UI only thing/For the showing it in the tree.

It's not just about displaying this feeds/items. For example, you select the 'untagged' tag from the treeview and select 'mark all as read' on the filtered article list. You need to supply the backend the information which items (more precisely which group/feed) do you wish to mark as read. Sure you can add something hardcoded for untagged items when generating the treeview and check for the existence of this value when it comes to mark items as read. But that is messy and prone to errors. And you would add this hardcoded value to multiple functions like 'count number of unread' and so on.

Well, and you would have to do the same for the fever api.

That's why I had the idea to assign a tag to every feed. Add it once and handle all feeds the same way. What do you think about it?

**Comment by mkresin** [comment]
You might want to check [my last contribution](https://github.com/miniflux/miniflux/commit/46d69b15f69b2ee895c4e0aba86561edd9fac8db) to miniflux. It illustrates really good what I mean with 'Add it once and handle all the same way'.

**Comment by kordianbruck** [comment]
> Yeah that's right. But you would have to implemented this logic to all functions that deal with feeds/tags. Even adding this 'information' by altering the result set of the database query needs to be done for more than one function.

The only places I can imagine this would be important is: Tree Menu, updating via Fever / UI mark as read. In both cases you could use one function which would use the treemenu function to get all feeds with their respective tags, then filter the ones which don't have one. Then use a update query with the `IN` operator. Sure this is some additional logic, but  as long as it's only the update function this should work just fine.

I've had bad experiences with assumptions on models (i.e. all uncategorized will have the according tag). On the contrary you would need some more logic in the purge/delete/update functions to prevent users from modifying the locked tag. Other developers might overlook this requirement easily.

> It's not just about displaying this feeds/items. For example, you select the 'untagged' tag from the treeview and select 'mark all as read' on the filtered article list. You need to supply the backend the information which items (more precisely which group/feed) do you wish to mark as read. Sure you can add something hardcoded for untagged items when generating the treeview and check for the existence of this value when it comes to mark items as read. But that is messy and prone to errors. And you would add this hardcoded value to multiple functions like 'count number of unread' and so on.

Same functionality you need to implement for the fever api. See above.

**Comment by mkresin** [comment]
What you describe sound as complex to me as expected. Special handling of Tree Menu, Fever, UI, new function, adjust output format of function to the actual needs, update statement with IN...

Have a look at https://github.com/mkresin/miniflux/commit/27baef3078695b22c39a01329c6eb4752dd7a021. Nothing more is needed for a 'default' tag. Keep in mind, it's not yet finished. Thats why it's in my working tree.

**Comment by kordianbruck** [comment]
You would need to add functions for the select and updating in any case. But alright, if you think this is the better way then merge the changes when you are done :+1:

**Comment by mkresin** [comment]
I revisited your arguments and you are right. It's a bad design to add this kind of logic/dependency to model.

Especially after I confirmed that my fever api client is capable of displaying tagged and untagged feeds side by side.

**Comment by kordianbruck** [comment]
We might have to revisit this, as not all clients might work the same way... we'll see.
