### ISSUE TITLE
Tag styling

### ISSUE THREAD

**Issue by kordianbruck** [kordianbruck/miniflux#2]
Buttons need some better styling. I like the Bootstrap btn-group class, maybe we could implement this here also.

**Comment by kordianbruck** [comment]
Picking up the suggestion from the other issue (https://github.com/kordianbruck/miniflux/issues/6#issuecomment-90745921), it would be a good idea to use check boxes instead of buttons with a hidden input. you save on the complexity and the JavaScript. 

Today check boxes are style able, so this should work just fine. Example @ http://jsfiddle.net/zAFND/4/

**Comment by mkresin** [comment]
Hey kordian,

based on your commit I've tried to do it by my self with minimal impact on existing code and ... failed.

![screenshot 250 edit subscription - mozilla firefox](https://cloud.githubusercontent.com/assets/4547948/7116520/5749c8a4-e1f2-11e4-945d-be661353083d.png)

Do you have an explanation what I'm missing? You can find the code here: https://github.com/mkresin/miniflux/commits/tags_button.
