### ISSUE TITLE
Tag colors

### ISSUE THREAD

**Issue by kordianbruck** [kordianbruck/miniflux#3]
Make all tags have unique colors which help identify the tags more easily

**Comment by kordianbruck** [comment]
Instead directly adding classes to the database and model, the new proposal is just numbering the order of buttons with a general class like item-1, item-2... item-n. 

@mkresin do you have an idea how to make sure so that the colors stay the same across all usages without adding a column to the db?

**Comment by mkresin** [comment]
It's only possible if we use the tag_id as postfix instead of sequential numbers.

But that has the drawback that you need a lot of entries in your css file if you decide to remove and add a lot of tags.

I'll need to check the sqlite docs in what cases ids are reused. Especially after https://github.com/kordianbruck/miniflux/commit/eeeb6dff364d98742075d96c1a922f313d9154d0.

**Comment by kordianbruck** [comment]
That's an idea, together with something [this](http://stackoverflow.com/questions/6127814/nth-child-with-mod-or-modulo-operator) it could work. Also without autoincrement the values for ids should get reassigned.

**Comment by mkresin** [comment]
I doubt that I understand your idea correctly.

When using `nth-child()`, the colouring is dependent on the alphabetical order. Means if you have B C D and add A, the colours are shifted by one to the left.

Generally it seams to be safe to use [nth-child()](http://caniuse.com/#search=nth-child%28%29)

**Comment by mkresin** [comment]
To address a specific button by the tag_id you can do it this way:

```
#taglist input[type="checkbox"][value="2"] + span {
    background-color: black;
}
```

where value is the tag_id. No need to introduce general classes like item-1, item-2... item-n.

**Comment by mkresin** [comment]
I don't think we should bundle coloured buttons with the default theme. You know, stay minimal.

But it's easily possible using a custom css file/theme as outlined by my last comments. What's your opinion on this?

**Comment by kordianbruck** [comment]
I would still like to implement this. I think if we find good, simple colors we can keep the minimalistic approach while ensuring ease of use. As I said before I think this makes the interface more recognizable.

**Comment by kordianbruck** [comment]
Keeping it simple, so no colors for now. Can be implemented in a later step. 

Closing this issue for now, so we can proceed to create a PR to the main repo.
