### ISSUE TITLE
remove tags from feeds

### ISSUE THREAD

**Issue by mkresin** [kordianbruck/miniflux#6]
Tags can't be removed from feeds at the moment.

**Comment by kordianbruck** [comment]
Possible UI for this action: http://www.itgeared.com/articles/1475-html5-drag-drop-tutorial/

**Comment by mkresin** [comment]
Now that we're talking about it, I have another idea.

What about showing all existing tags and assign/remove a tag by clicking on it. Something like this:

![unbenannt](https://cloud.githubusercontent.com/assets/4547948/7034120/9e0b2e4e-dd7f-11e4-805f-7fae98b9417e.png)

Blue: assigned Tag
Gray: available but unassigned Tag

The coloring isn't optimal, since it's hard to guest which color means active and which color means inactive. But it's only meant as illustration.

`New` allows to add a not existing tag. Beside the `New` functionality, it would even work without javascript, by using form fields.

Most of the miniflux functions do work without javascript. I don't now whether the non-javascript fallback is intended, desired or required. @fguillot would you please enlighten me?

The implementation of this should be really easy and lightweight.

would fix #5 as well.

**Comment by kordianbruck** [comment]
That actually is the idea and the way I have implemented it, but the active state of the buttons isn't too good currently. As I said this needs some work still.

#5 is a Bug, which I didn't intend. I will fix this in the comming days.

**Comment by mkresin** [comment]
Great. But for what purpose we need the html5 drag'n'drop stuff from the link then?

**Comment by kordianbruck** [comment]
Well, if you want to get rid of tag completly, which you won't use anymore, you can't actually do this currently. So if you have a typo in a tag title, it will stay there for ever. 

You could then just drag that tag to the trash can and so remove the tag from the DB

**Comment by mkresin** [comment]
Why not purge tags that are no longer used automatically? We could check whether a tag is orphaned when any feed is saved.

As written in the first comment, my issue was that I couldn't remove a particular tag from a feed. It's not about removing tags at all.

**Comment by mkresin** [comment]
IMHO the easiest would be to use checkboxes instead of buttons for the tags. They can be easily styled as buttons and work great with forms:

http://jsfiddle.net/zAFND/4/
http://jsfiddle.net/zAFND/2/

And the best of all, no new javascript or anything else is needed.
