### ISSUE TITLE
Expose Tags via Fever API

### ISSUE THREAD

**Issue by mkresin** [kordianbruck/miniflux#9]

**Comment by kordianbruck** [comment]
According to http://feedafever.com/api this would only need changes in the following end points:
- feeds
- groups
- write_groups

1 & 2 both have feeds_groups in common. Should be a quick task, let me know if you need assistance.

**Comment by mkresin** [comment]
1 & 2 is already implemented in my working tree, but I have not had sufficient time to test the changes with a fever client.

3 depends on #10 and need changes to the feed model.

On the long run, I'm thinking about rewriting the `fever/index.php`, to make use of the existing feed model instead of breaking with MVC and mixing everything together. The fever endpoint should be an controller. That's why I don't want to add more sql (model) stuff to the fever API endpoint.

**Comment by kordianbruck** [comment]
Why don't you push it to the repo then I can test it out as well. Then I could also try to implement #10 without the tag and see how complex it gets...

I think the issue being that the fever api login is different from the normal authentication of miniflux, didn't look into this yet though. Surely merging it into a controller would be awesome! Should we pick it up as an issue?

**Comment by mkresin** [comment]
As written before, It's not even tested by my self. I don't want to push untested code to the repo.

**Comment by mkresin** [comment]
Status update:
- Tags are exposed and if an item get marked within one tag, it get marked all other tags as well
- marking a group as read doesn't work yet
